version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URI=mongodb+srv://augustoalejandro95:2jPsaQHW3K8y9TST@cluster0.xe2iqf9.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=local-development-jwt-secret
    command: uvicorn app.api:app --host 0.0.0.0 --port 3001 --reload
